import type { NextPage } from "next";
import { SignInButton, SignOutButton, useAuth, useUser } from "@clerk/nextjs";

import Head from "next/head";
import Recipes from "~/components/Recipes";

import { api } from "~/utils/api";

import styles from "./index.module.css";

const Home: NextPage = () => {
  const { isSignedIn } = useAuth();
  const { user } = useUser();

  // start fetching recipes right away
  api.recipes.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isSignedIn && !!user && (
          <div>
            <h1>Hello {user.firstName}</h1>
            <SignOutButton />
          </div>
        )}
        {!isSignedIn && !user?.id && (
          <div>
            <SignInButton />
          </div>
        )}
        <Recipes />
      </main>
    </>
  );
};

export default Home;
