import type { NextPage } from "next";
import { CategoryType } from "@prisma/client";

import Head from "next/head";
import { useState } from "react";
import { Categories } from "~/components/Categories";
import { Recipes } from "~/components/Recipes";
import { Spacer } from "~/components/Spacer";

import { api } from "~/utils/api";

import styles from "../styles/modules/Home.module.scss";

// const categoryTypes = Object.values(CategoryType);

const Home: NextPage = () => {
  const [category, setCategory] = useState<{ selected: CategoryType }>({
    selected: "ALL",
  });
  // start fetching recipes right away
  api.recipes.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Recipes</h1>
        <Spacer height={45} />
        <Categories category={category} setCategory={setCategory} />
        <Spacer height={45} />
        <Recipes category={category} />
      </main>
    </>
  );
};

export default Home;
